{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (E:\\js\\ReactNativeBot\\node_modules\\mongodb-core\\lib\\topologies\\server.js:326:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (E:\\js\\ReactNativeBot\\node_modules\\mongodb-core\\lib\\connection\\pool.js:270:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (E:\\js\\ReactNativeBot\\node_modules\\mongodb-core\\lib\\connection\\connection.js:175:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-04-06T07:24:10.344Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (E:\\js\\ReactNativeBot\\node_modules\\mongodb-core\\lib\\topologies\\server.js:326:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (E:\\js\\ReactNativeBot\\node_modules\\mongodb-core\\lib\\connection\\pool.js:270:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (E:\\js\\ReactNativeBot\\node_modules\\mongodb-core\\lib\\connection\\connection.js:175:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-04-06T07:24:10.357Z"}
